### ISSUE TITLE
Remove `BundleID` requirement for import

### ISSUE THREAD

**Issue by drgrib** [deanishe/awgo#2]
The choice of design on [this line](https://github.com/deanishe/awgo/blob/a6e12de3fd600c931583c6c69cb54c2553b68371/workflow.go#L45) makes this package and any program that uses it unnecessarily hard to test. It gives no opportunity to check and prepare for a testing situation programmatically before `awgo` is imported.

A better approach would be to have a function like this:

``` go
func InitWorkflow() {
	wf = New()
}
```

This gives users an opportunity to set the environment variables in `env.sh` for testing after the package is imported. Here is one approach:

``` go
func main() {
	if len(os.Args) < 2 {
		InitEnvShVariables()
	}
	aw.InitWorkflow()
	aw.Run(run)
}
```

The way it is currently set up, I'm blocked by the `BundleID` error immediately on import if I run my program in a testing environment outside of Alfred without first running `env.sh`.

I'm currently trying to edit logic in my program that has nothing to do with `awgo` so it is annoying to be blocked by it simply because I'm importing it.

**Comment by deanishe** [comment]
> A better approach would be to have a function like this

`wf = New()` is there to allow the library-level functions to work without you having to create your own `Workflow`. Requiring an `InitWorkflow()` function to be called rather defeats the purpose of that, so no-go.

I agree that import-time side effects suck. Either I will make initialisation lazier or strip out the library-level functions and the default `wf` Workflow.

**Comment by drgrib** [comment]
> Requiring an InitWorkflow() function to be called rather defeats the purpose of that, so no-go.

Another option would be to have flexible default behavior for the built-in `Workflow`. I.e. have it detect that the developer hasn't put it inside a real bundle yet and have it automatically skip bundle management tasks like caching. That way they can rapidly develop the parts of the `Workflow` for user interaction using `stdout`. Then once the program is fully polished, it can be built into an executable for use in the real Alfred bundle.

This option may be preferable because it means you don't have to change the syntax for your `awgo` package and current developers can experience this benefit free of charge without changing their current code. It's honestly how I expected the package to behave when I first downloaded it and I was surprised when it started hitting me with `BundleID` errors for trying to develop locally through `stdout`. This seems like the most reasonable default behavior.

**Comment by deanishe** [comment]
> That way they can rapidly develop the user interaction parts of the Workflow using stdout

I always use a terminal to develop workflows. It's simple enough to source [a script that sets the required variables](https://github.com/deanishe/alfred-safari-assistant/blob/master/alfred_env.sh).

I will remove the import-time requirement for a bundle ID because no library should explode on import. The runtime requirement will remain, however. AwGo *needs* the bundle ID (and cache path) for most of its functionality.

> it means you don't have to change the syntax for your awgo package and current developers can experience this benefit free of charge without changing their current code

Too late for that, I'm afraid. I've refactored AwGo massively in the v0.14 branch.

Check out the new [`Env`](https://github.com/deanishe/awgo/blob/49bf067d5c079058ebd7f5578d16431ab50d6305/alfred_config.go#L19) interface that now underpins everything.

Currently, the [`Option` to pass a custom `Env` to `New()`](https://github.com/deanishe/awgo/blob/49bf067d5c079058ebd7f5578d16431ab50d6305/workflow_options.go#L203) isn't exported, but I'll change that (and rejigger `New()` not to immediately panic if the environment variables are missing).

Then you can pass your own `Env` to `New()` to set the bundle ID etc. programatically. I'll probably export the [`mapEnv`](https://github.com/deanishe/awgo/blob/49bf067d5c079058ebd7f5578d16431ab50d6305/testutils_test.go#L19) type to make it even easier.

**Comment by deanishe** [comment]
The default *Workflow and import-time requirements are gone in v0.14.
