### ISSUE TITLE
Can maybe use gon library to notarize binaries

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/awgo#23]
I came across this library:

https://github.com/mitchellh/gon 

And it got me thinking if it would be possible for AwGo to perhaps do this notarization step on its own and have the resulting binaries it produces be notarized and thus avoid issues like

https://github.com/deanishe/awgo/wiki/Catalina

Maybe this is not possible, just a thought. Love AwGo lib.

**Comment by deanishe** [comment]
Good find, but that doesn't look at all straightforward to do.

More importantly, from my point of view, the problem is that you need to have a paid Apple developer account to generate a signature that Catalina will accept. As a matter of principle, Apple can go fuck themselves if they think I'm paying them for the "privilege" of being able to write open-source software for their platform.

So far, this solution suggested by @baa76 looks like the best way:
![](https://camo.githubusercontent.com/b55fc11fea93412751925c0bf23d4d8fabeade6d/68747470733a2f2f636f6e74656e742e696e766973696f6e6369632e636f6d2f723232393439312f6d6f6e74686c795f323031395f31312f696d6167652e706e672e34336561656162616332326136376461626234386439366534313961393431612e706e67 "")
That should cover all workflows. If a couple more users can confirm that works for them, I'll update the wiki.
